TOUCHWATCH_PATH = None
TOUCHWATCH_FOLDER = None
TOUCHWATCH_COLOUR = "red"
TOUCHWATCH_POLLING_DELAY = 1000
TOUCHWATCH_PATTERN = ["*.py"]
TOUCHWATCH_IGNORE_PATTERN = None
TOUCHWATCH_IGNORE_DIRECTORIES = None
TOUCHWATCH_CASESENSITIVE = True